version: '3.1'

services:
  db:
    image: ${DOCKER_REGISTRY}postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_store:/var/lib/postgresql/data

  redis:
    image: ${DOCKER_REGISTRY}redis
    ports:
      - 6379:6379
    env_file:
      - .env

volumes:
  pg_store:
