version: '3.1'

services:
  nginx:
    ports:
      - 80:80
    build:
      context: ./etc/nginx/
      dockerfile: Dockerfile
      args:
        - DOCKER_REGISTRY
        - PIP_INDEX_URL
        - PIP_TRUSTED_HOST
    volumes:
      - static_store:/opt/app/public
    depends_on:
      - web

  web:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_REGISTRY
        - PIP_INDEX_URL
        - PIP_TRUSTED_HOST
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["web"]
    volumes:
      - static_store:/opt/app/public

  db:
    image: ${DOCKER_REGISTRY}postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_store:/var/lib/postgresql/data

  redis:
    image: ${DOCKER_REGISTRY}redis
    ports:
      - 6379:6379
    env_file:
      - .env

volumes:
  static_store:
  pg_store: