# Generated by Django 3.1.5 on 2021-03-31 12:14

from django.db import migrations


def create_homepage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    Locale = apps.get_model('wagtailcore.Locale')
    HomePage = apps.get_model('home.HomePage')

    Page.objects.filter(id=2).delete()

    locale, _ = Locale.objects.get_or_create(language_code='ru')

    homepage_content_type, _ = ContentType.objects.get_or_create(model='homepage', app_label='home')

    homepage = HomePage.objects.create(
        title="Домашняя страница",
        draft_title="Домашняя страница",
        slug='home',
        content_type=homepage_content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/home/',
        locale=locale
    )

    Site.objects.create(hostname='Сайт по умолчанию', root_page=homepage, is_default_site=True)


def remove_homepage(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    HomePage = apps.get_model('home.HomePage')

    HomePage.objects.filter(slug='home', depth=2).delete()
    ContentType.objects.filter(model='homepage', app_label='home').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_homepage, remove_homepage),
    ]
